# Generated by Django 4.2.8 on 2023-12-17 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='author',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='description',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='price',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='title',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='trailer',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_author',
            field=models.TextField(max_length=1000, null=True, verbose_name='Авторы фильма'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание фильма'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_genre',
            field=models.CharField(choices=[('Аниме', 'Аниме'), ('Исторический', 'Исторический'), ('Боевик', 'Боевик'), ('Детектив', 'Детектив'), ('Криминал', 'Криминал'), ('Ужасы', 'Ужасы'), ('Мелодрама', 'Мелодрама'), ('Фантастика', 'Фантастика')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_image',
            field=models.ImageField(null=True, upload_to='movies/', verbose_name='Добавьте фото'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_price',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(2500)], verbose_name='Укажите цену'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_title',
            field=models.CharField(max_length=100, null=True, verbose_name='Название фильма'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_trailer',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на трейлер фильма'),
        ),
    ]
